title: Surtu Kirjastus
email: c
description: >- # this means to ignore newlines until "baseurl:"
  surtu
tagline: Surtu Kirjastus
baseurl: "" 
url: "https://surtu.ee" 
permalink: pretty
lang: en-US
timezone: Europe/London
author: Surtu

book:
- title: te

# Build settings
#theme: default
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - FUNDING.md
