title: Surtu Kirjastus
email: c@c.com
description: >- # this means to ignore newlines until "baseurl:"
  21. sajandi raamatu- ja muusikakirjastus
tagline: Surtu Kirjastus
baseurl: "" 
url: "https://surtu.ee" 
permalink: pretty
paginate: 2
lang: et
timezone: Europe/London
author: Surtu

books:
- title: Test
  pic: /assets/images/esikaas-679x960.png
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
  buy-link: 
- title: another one
  pic:
  description: Testing testing lorem ipsum teuom
  buy-link: https://hen.ee

music:
- title: GJ - muusikapala
  year: 2022
  pic: /assets/images/esikaas-679x960.png
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  link: 

salvestused:
- title: GJ - Salvestusene
  year: 2022
  pic: /assets/images/esikaas-679x960.png
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  link: https://hen.ee

# Build settings
#theme: default
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag
#  - jekyll-multiple-languages-plugin

#languages: ["et", "en"]
#exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - FUNDING.md
