title: Surtu Kirjastus
email: c@c.com
description: >- # this means to ignore newlines until "baseurl:"
  21. sajandi raamatu- ja muusikakirjastus
tagline: Surtu Kirjastus
baseurl: "" 
url: "https://surtu.ee" 
permalink: pretty
lang: et
timezone: Europe/London
author: Surtu

book:
- title: te

# Build settings
#theme: default
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

languages: ["et", "en"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - FUNDING.md
